services:
  postgres:
    image: docker.io/postgres:alpine
    container_name: postgres-thd
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_INITDB_ARGS: "--encoding=UTF8 --lc-collate=C --lc-ctype=C"
      PGUSER: postgres
      POSTGRES_USER: postgres
    healthcheck:
        test: ["CMD-SHELL", "pg_isready", "-U","-q", "postgres", "-d", "postgres"]
    volumes:
      - ./data:/var/lib/postgresql/data
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
    networks:
      - pg-thd

  pgadmin:
    image: docker.io/dpage/pgadmin4:latest
    container_name: pgadmin
    restart: always
    environment:
      ## email address used when setting up the initial administrator account
      PGADMIN_DEFAULT_EMAIL: ${MAIL}
      ## password used when setting up the initial administrator account
      PGADMIN_DEFAULT_PASSWORD: ${ADMINPASS}
      ## the Postfix server will not be started
      PGADMIN_DISABLE_POSTFIX: 'True'
    entrypoint: /bin/sh -c "chmod -R 777 /var/lib/pgadmin;chmod 600 /pgadmin4/config_distro.py; /entrypoint.sh;"
    user: "root"
    configs:
      - source: config_distro.py
        target: /pgadmin4/config_distro.py
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./pgadmin:/var/lib/pgadmin
    labels:
      - traefik.enable=true
      - traefik.http.routers.pgadmin.rule=Host(`pgadmin.${DOMAIN}`)
      - traefik.http.routers.pgadmin.entrypoints=websecure
      - traefik.http.routers.pgadmin.tls=true
      - traefik.http.routers.pgadmin.service=pgadmin
      - traefik.http.services.pgadmin.loadbalancer.server.port=80
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
    networks:
      - pg-thd
      - cloudflaretunnel

networks:
  pg-thd:
  cloudflaretunnel:
    external: true
