tunnel: 5ccf04f9-f485-4a6b-8680-48fd823beef4
credentials-file: /etc/cloudflared/5ccf04f9-f485-4a6b-8680-48fd823beef4.json
ingress:
  - hostname: '*.let-net.cc'
    service: https://traefik
    originRequest:
      originServerName: '*.let-net.cc'
      http2Origin: true
      noTLSVerify: true
  - hostname: 'let-net.cc'
    service: https://traefik
    originRequest:
      originServerName: 'let-net.cc'
      http2Origin: true
      noTLSVerify: true
  - service: http_status:404
